### ISSUE TITLE
建议不要呆在捷径社区

### ISSUE THREAD

**Issue by bukaixyz** [F7YM/pycommand#1]
捷径社区就是一个恶臭的垃圾社区，里面都是骗子和小学生，谜底也不关心了 骗子kiko贿赂谜底员工 胡乱管理🌝，社区风气极差，UI极差 服务器，代码全方位差！

我们衷心劝告你不要呆在捷径社区里面！

如果你不听我的建议 我也没办法 SFA迟早会与谜底开战 根除捷径社区，骗子等恶势力！选择权在你手上🌝

皇帝睿

捷径自由联盟SFA

捷径宝议会

5月4日

**Comment by bukaixyz** [comment]
![image](https://user-images.githubusercontent.com/85857425/236254259-9c6d8ca2-032a-42e7-bc08-44223175c1c8.jpeg)

**Comment by F7YM** [comment]
随意

**Comment by bukaixyz** [comment]
现在弃坑确实是一个很好的选择🌝 SFA会让谜底倒闭的，放心吧，绝对不会辜负老姨夫的期望🌝

**Comment by bukaixyz** [comment]
我也彻底对快捷指令失去兴趣了，🌝
我有新iPad了（第10代，A14），炫耀一下🌚😍

**Comment by F7YM** [comment]
已经半退了
反正与我无瓜

**Comment by bukaixyz** [comment]
> 已经半退了
> 
> 反正与我无瓜

我投诉了捷径社区app🌝

此app中有侵犯他人版权的“捷径”，例如，可以在app中搜索到bilibili,twitter，腾讯视频等平台的视频下载，解析工具，甚至可以破解平台的付费内容，也有破解小米运动的违法工具！
此外，此app中的“社区”中有大量讨论如何破解其他软件，平台的内容，也有讨论VPN链接中国大陆禁止的网站，服务的工具，方法，以及有歧视小学生的仇恨言论！
不仅如此，此app中还有诈骗内容，有些app的认证用户（kiko)把免费的ChatGPT拿来卖钱，且把上述破解twitter 视频的工具作为付费，诱导其他用户付款！
总之，开发商杭州谜底科技有限公司已放任此app不管，若贵公司放任此app继续在App Store上架 损害的不仅是用户，其他开发商的利益，也损害贵公司的名誉！
最后，作为Apple的忠实粉丝，我恳切希望贵公司严肃处理此app,提高App Store的信誉。

**Comment by F7YM** [comment]
你把投诉给苹果了？

**Comment by bukaixyz** [comment]
> 你把投诉给苹果了？

投诉了🌝

**Comment by bukaixyz** [comment]
http://sfas.nndx.ml/bbs/public/

社区弄好了🌝

**Comment by bukaixyz** [comment]
[捷径盒提前彻底倒闭了🌝](http://sfas.nndx.ml/bbs/public/d/3)

**Comment by bukaixyz** [comment]
SFA近期与捷径社区交战规模较大 告知一下 想知道相信信息回复这个评论🌝

**Comment by F7YM** [comment]
说吧

**Comment by bukaixyz** [comment]
> 说吧

我投诉成功了捷径社区骗子的小程序 gitee api,去AdGuard 的GitHub上让他们把捷径社区加到过滤器中 然后一堆捷径社区绿色通道的人就在那里胡说八道 又谷歌搜了我的一堆账号 利用骗子捷径后门 导致我iPad设备名泄漏，并收集了我的大量账号信息（包括我的真实姓名），然后在捷径社区这个恶臭的垃圾社区里面发帖子 公开我的信息 并侮辱，威胁我🌝

**Comment by F7YM** [comment]
无所谓
我声明：我不会参加这场争斗

**Comment by F7YM** [comment]
我看了一下社区，确实有不少人受到了影响

**Comment by bukaixyz** [comment]
> 我看了一下社区，确实有不少人受到了影响

所以SFA电子战联军军方还是有实力的😁我就看捷径社区和里面的人不顺眼🌝😡
尤其是kiko这个智障，天天侵犯其他公司利益，违法犯罪，还在狂妄自大，胡乱发疯🌝
另外，显示投诉成功了 但是捷径社区微信小程序仍然能用 奇奇怪怪的🌝

**Comment by bukaixyz** [comment]
我把捷径社区微信小程序也弄掉了🌝

**Comment by F7YM** [comment]
你们sfa有多少人🙃

**Comment by bukaixyz** [comment]
> 你们sfa有多少人🙃

2个人🌝

除了我之外还有Richbean 捷径盒用户名“长毛的狗狗”，赚钱游戏作者🌝他是SFA成员组织“捷径宝”的捷径宝战略指挥官🌝

**Comment by F7YM** [comment]
🫠没什么好评价的
没事来Github作点贡献🌚

**Comment by bukaixyz** [comment]
我骂了捷径社区一堆智障 可以看看🌝

https://github.com/AdguardTeam/AdguardFilters/issues/151551

**Comment by F7YM** [comment]
把捷径社区添加进拦截器？

**Comment by F7YM** [comment]
> 我骂了捷径社区一堆智障 可以看看🌝
> 
> [AdguardTeam/AdguardFilters#151551](https://github.com/AdguardTeam/AdguardFilters/issues/151551)

🤔

**Comment by bukaixyz** [comment]
> 把捷径社区添加进拦截器？

确实🌝我现在把捷径社区一堆神经病的GitHub账号拉黑并投诉了，干脆直接向Adguard提交PR🌝 https://github.com/AdguardTeam/AdguardFilters/pull/152049

**Comment by F7YM** [comment]
> 我骂了捷径社区一堆智障 可以看看🌝
> 
> [AdguardTeam/AdguardFilters#151551](https://github.com/AdguardTeam/AdguardFilters/issues/151551)

没必须直接撕破脸开骂吧🌚

**Comment by F7YM** [comment]
> > 把捷径社区添加进拦截器？
> 
> 确实🌝我现在把捷径社区一堆神经病的GitHub账号拉黑并投诉了，干脆直接向Adguard提交PR🌝 [AdguardTeam/AdguardFilters#152049](https://github.com/AdguardTeam/AdguardFilters/pull/152049)

这……

**Comment by bukaixyz** [comment]
> > 我骂了捷径社区一堆智障 可以看看🌝
> 
> > 
> 
> > [AdguardTeam/AdguardFilters#151551](https://github.com/AdguardTeam/AdguardFilters/issues/151551)
> 
> 
> 
> 没必须直接撕破脸开骂吧🌚

不骂怎么办呢 看不顺眼🌝

**Comment by F7YM** [comment]
不用管呗🌚
你总不能直接开户吧

**Comment by F7YM** [comment]
> > 把捷径社区添加进拦截器？
> 
> 确实🌝我现在把捷径社区一堆神经病的GitHub账号拉黑并投诉了，干脆直接向Adguard提交PR🌝 [AdguardTeam/AdguardFilters#152049](https://github.com/AdguardTeam/AdguardFilters/pull/152049)

就算拦截……我也不用捷径社区
没影响🌚🌚🌚

**Comment by bukaixyz** [comment]
建议不要在捷径社区更新捷径🌝快倒闭了🌝

**Comment by F7YM** [comment]
……没地方更了

**Comment by bukaixyz** [comment]
> ……没地方更了

不更新不就行了🌚
